# FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
# WORKDIR /app
# COPY ./SpyderWeb/SpyderWeb ./
# ENTRYPOINT ["dotnet", "SpyderWeb.dll"]

FROM mcr.microsoft.com/dotnet/core/sdk:2.2 AS build
WORKDIR /app

COPY * ./
RUN ls -l .
RUN dotnet publish SpyderWeb.csproj -c Release -o out


FROM mcr.microsoft.com/dotnet/core/aspnet:2.2 AS runtime
WORKDIR /app
COPY --from=build /app/SpyderWeb/out ./
ENTRYPOINT ["dotnet", "SpyderWeb.dll"]